export const vocabularyPairs = [
  { id: 1, word: "צַּבַּאח אִלְחֵ'יר", translation: "בוקר טוב" },
  { id: 2, word: "צַּבַּאח אִלְנוּר", translation: "בוקר אור" },
  { id: 3, word: "מַסַא אִלְחֵ'יר", translation: "ערב טוב" },
  { id: 4, word: "מַסַא אִלְנוּר", translation: "ערב אור" },
  { id: 5, word: "מַרְחַבַּא", translation: "שלום רב" },
  { id: 6, word: "מַרְחַבְּתֵין", translation: "רב שלומות" },
  { id: 7, word: "אַהְלַן וְסַהְלַן", translation: "שלום וברכה" },
  { id: 8, word: "אַהְלַן וְסַהְלַן בִּיכּ", translation: "שלום וברכה לך" },
  { id: 9, word: "אִסֵם", translation: "שם" },
  { id: 10, word: "אַסַאמִי", translation: "שמות" },
  { id: 11, word: "אַמִיר", translation: "נסיך" },
  { id: 12, word: "אֻמַרַא", translation: "נסיכים" },
  { id: 13, word: "מְעַלֵם", translation: "מורה (זכר)" },
  { id: 14, word: "מְעַלְמִין", translation: "מורים" },
  { id: 15, word: "מְעַלְמֵה", translation: "מורה (נקבה)" },
  { id: 16, word: "מְעַלְמַאת", translation: "מורות" },
  { id: 17, word: "פִי", translation: "ב..." },
  { id: 18, word: "מַע", translation: "עם" },
  { id: 19, word: "דַוְרַה", translation: "קורס" },
  { id: 20, word: "דַוְרַאת", translation: "קורסים" },
  { id: 21, word: "טַאלֵבּ", translation: "סטודנט" },
  { id: 22, word: "טֻלַאבּ", translation: "סטודנטים" },
  { id: 23, word: "טַאלְבֵּה", translation: "סטודנטית" },
  { id: 24, word: "טַאלִבַּאת", translation: "סטודנטיות" },
  { id: 25, word: "גַ'אמְעַה", translation: "אוניברסיטה" },
  { id: 26, word: "גַ'אמִעַאת", translation: "אוניברסיטאות" },
  { id: 27, word: "סֵכְּרֵתֵירַא", translation: "מזכירה" },
  { id: 28, word: "סֵכְּרֵתֵירַאת", translation: "מזכירות" },
  { id: 29, word: "סֵכְּרֵתֵיר", translation: "מזכיר" },
  { id: 30, word: "סֵכְּרֵתֵירִיוּן", translation: "מזכירים" },
  { id: 31, word: "אַמִין", translation: "מזכיר של גוף רשמי, ישר/אמין" },
  { id: 32, word: "אַמִינֵה", translation: "מזכירה של גוף רשמי, ישרה/אמינה" },
  { id: 33, word: "מַדְרַסֵה", translation: "בית ספר" },
  { id: 34, word: "מַדַארֵס", translation: "בתי ספר" },
  { id: 35, word: "מֻדִיר", translation: "מנהל" },
  { id: 36, word: "מֻדַרַא", translation: "מנהלים" },
  { id: 37, word: "מֻדִירֵה", translation: "מנהלת" },
  { id: 38, word: "מֻדִירַאת", translation: "מנהלות" },
  { id: 39, word: "שִרְכֵּה", translation: "חברה" },
  { id: 40, word: "שַרִכַּאת", translation: "חברות" },
  { id: 41, word: "מֻחַאמִי", translation: "עו\"ד" },
  { id: 42, word: "מֻחַאמִיֵין", translation: "עורכי דין" },
  { id: 43, word: "מֻחַאמִיֵה", translation: "עורכת דין" },
  { id: 44, word: "מֻחַאמִיַאת", translation: "עורכות דין" },
  { id: 45, word: "וִזַארַה", translation: "משרד ממשלתי" },
  { id: 46, word: "וִזַארַאת", translation: "משרדי ממשלה" },
  { id: 47, word: "עַדֵל", translation: "צדק" },
  { id: 48, word: "תִלְמִיז", translation: "תלמיד" },
  { id: 49, word: "תַלַאמִיז", translation: "תלמידים" },
  { id: 50, word: "תִלְמִיזֵה", translation: "תלמידה" },
  { id: 51, word: "תִלְמִיזַאת", translation: "תלמידות" },
  { id: 52, word: "צַאחֵבּ", translation: "חבר" },
  { id: 53, word: "אַצְחַאבּ", translation: "חברים" },
  { id: 54, word: "צַאחְבֵּה", translation: "חברה (ידידה)" },
  { id: 55, word: "צַאחְבַּאת", translation: "חברות" },
  { id: 56, word: "דַאר", translation: "בית" },
  { id: 57, word: "דוּר", translation: "בתים" },
  { id: 58, word: "וַלַד", translation: "ילד" },
  { id: 59, word: "וְלַאד", translation: "ילדים" },
  { id: 60, word: "אִבֵּן", translation: "בן" },
  { id: 61, word: "אַבְּנַאא", translation: "בנים" },
  { id: 62, word: "בִּנְת", translation: "ילדה / בת" },
  { id: 63, word: "בַּנַאת", translation: "ילדות / בנות" },
];

export default vocabularyPairs;
