export const vocabularyPairs = [
  { id: 1, word: "צַּבַּאח אִלְחֵ'יר", translation: "בוקר טוב" },
  { id: 2, word: "צַּבַּאח אִלְנוּר", translation: "בוקר אור" },
  { id: 3, word: "מַסַא אִלְחֵ'יר", translation: "ערב טוב" },
  { id: 4, word: "מַסַא אִלְנוּר", translation: "ערב אור" },
  { id: 5, word: "מַרְחַבַּא", translation: "שלום רב" },
  { id: 6, word: "מַרְחַבְּתֵין", translation: "רב שלומות" },
  { id: 7, word: "אַהְלַן וְסַהְלַן", translation: "שלום וברכה" },
  { id: 8, word: "אַהְלַן וְסַהְלַן בִּיכּ", translation: "שלום וברכה לך" },
  { id: 9, word: "אִסֵם", translation: "שם" },
  { id: 10, word: "אַסַאמִי", translation: "שמות" },
  { id: 11, word: "אַמִיר", translation: "נסיך" },
  { id: 12, word: "אֻמַרַא", translation: "נסיכים" },
  { id: 13, word: "מְעַלֵם", translation: "מורה (זכר)" },
  { id: 14, word: "מְעַלְמִין", translation: "מורים" },
  { id: 15, word: "מְעַלְמֵה", translation: "מורה (נקבה)" },
  { id: 16, word: "מְעַלְמַאת", translation: "מורות" },
  { id: 17, word: "פִי", translation: "ב..." },
  { id: 18, word: "מַע", translation: "עם" },
  { id: 19, word: "דַוְרַה", translation: "קורס" },
  { id: 20, word: "דַוְרַאת", translation: "קורסים" },
  { id: 21, word: "טַאלֵבּ", translation: "סטודנט" },
  { id: 22, word: "טֻלַאבּ", translation: "סטודנטים" },
  { id: 23, word: "טַאלְבֵּה", translation: "סטודנטית" },
  { id: 24, word: "טַאלִבַּאת", translation: "סטודנטיות" },
  { id: 25, word: "גַ'אמְעַה", translation: "אוניברסיטה" },
  { id: 26, word: "גַ'אמִעַאת", translation: "אוניברסיטאות" },
  { id: 27, word: "סֵכְּרֵתֵירַא", translation: "מזכירה" },
  { id: 28, word: "סֵכְּרֵתֵירַאת", translation: "מזכירות" },
  { id: 29, word: "סֵכְּרֵתֵיר", translation: "מזכיר" },
  { id: 30, word: "סֵכְּרֵתֵירִיוּן", translation: "מזכירים" },
  { id: 31, word: "אַמִין", translation: "מזכיר של גוף רשמי, ישר/אמין" },
  { id: 32, word: "אַמִינֵה", translation: "מזכירה של גוף רשמי, ישרה/אמינה" },
  { id: 33, word: "מַדְרַסֵה", translation: "בית ספר" },
  { id: 34, word: "מַדַארֵס", translation: "בתי ספר" },
  { id: 35, word: "מֻדִיר", translation: "מנהל" },
  { id: 36, word: "מֻדַרַא", translation: "מנהלים" },
  { id: 37, word: "מֻדִירֵה", translation: "מנהלת" },
  { id: 38, word: "מֻדִירַאת", translation: "מנהלות" },
  { id: 39, word: "שִרְכֵּה", translation: "חברה" },
  { id: 40, word: "שַרִכַּאת", translation: "חברות" },
  { id: 41, word: "מֻחַאמִי", translation: "עו\"ד" },
  { id: 42, word: "מֻחַאמִיֵין", translation: "עורכי דין" },
  { id: 43, word: "מֻחַאמִיֵה", translation: "עורכת דין" },
  { id: 44, word: "מֻחַאמִיַאת", translation: "עורכות דין" },
  { id: 45, word: "וִזַארַה", translation: "משרד ממשלתי" },
  { id: 46, word: "וִזַארַאת", translation: "משרדי ממשלה" },
  { id: 47, word: "עַדֵל", translation: "צדק" },
  { id: 48, word: "תִלְמִיז", translation: "תלמיד" },
  { id: 49, word: "תַלַאמִיז", translation: "תלמידים" },
  { id: 50, word: "תִלְמִיזֵה", translation: "תלמידה" },
  { id: 51, word: "תִלְמִיזַאת", translation: "תלמידות" },
  { id: 52, word: "צַאחֵבּ", translation: "חבר" },
  { id: 53, word: "אַצְחַאבּ", translation: "חברים" },
  { id: 54, word: "צַאחְבֵּה", translation: "חברה (ידידה)" },
  { id: 55, word: "צַאחְבַּאת", translation: "חברות" },
  { id: 56, word: "דַאר", translation: "בית" },
  { id: 57, word: "דוּר", translation: "בתים" },
  { id: 58, word: "וַלַד", translation: "ילד" },
  { id: 59, word: "וְלַאד", translation: "ילדים" },
  { id: 60, word: "אִבֵּן", translation: "בן" },
  { id: 61, word: "אַבְּנַאא", translation: "בנים" },
  { id: 62, word: "בִּנְת", translation: "ילדה / בת" },
  { id: 63, word: "בַּנַאת", translation: "ילדות / בנות" },
  { id: 64, word: "פֻל", translation: "יסמין"},
  { id: 65, word: "זֵית", translation: "זֵית" },
  { id: 66, word: "קַמִיצ", translation: "חולצה" },
  { id: 67, word: "הַאדַא/הַאד", translation: "זה / הזה" },
  { id: 68, word: "הַדַאּכ", translation: "הוא / ההוא" },
  { id: 69, word: "הַאדִי/הַאיְ", translation: "זאת / הזאת" },
  { id: 70, word: "הַדִיּכ", translation: "היא / ההיא" },
  { id: 71, word: "הַדֹולַא/הַדֹול", translation: "אלו / האלו" },
  { id: 72, word: "הַדֹולַאּכ", translation: "הם / ההם / הן" },
  { id: 46, word: "דֻכַאן/דַכַּאּכִין", translation: "חנות/חנויות" },
  { id: 47, word: "מַ חַ ל/מַ חַ לאת", translation: "מקום/מקומות" },
  { id: 48, word: "סֻאַאל/אַסְאִלֵה, סֻאַאלַאת", translation: "שאלה/שאלות" },
  { id: 49, word: "גַ'וַאּב/אַ גְ 'וִ ּבֵ ה, גַ'וַאּבַ את", translation: "תשובה/תשובות" },
  { id: 50, word: "מַטַאר/מַטַארַאת", translation: "שדה תעופה/שדות תעופה" },
  { id: 51, word: "שֻ עֻ'ל/אַשְעַ'אל", translation: "עבודה/עבודות" },
  { id: 52, word: "ּבַ לַד/ּבֻלְדַ אן", translation: "יישוב/ישובים" },
  { id: 53, word: "דֹולֵה/דֻוַל", translation: "מדינה/מדינות" },
  { id: 54, word: "מַ דִינֵה/מֻ דֻן", translation: "עיר/ערים" },
  { id: 55, word: "קַרְיֵה/קֻרַא", translation: "כפר/כפרים" },
  { id: 56, word: "מִ נְטַ קַ ה/מַ נַאטֵ ק", translation: "אזור/אזורים" },
  { id: 57, word: "שַארֵע/שַוַארֵע", translation: "רחוב/רחובות" },
  { id: 58, word: "סַ אּכֵן/סַ אּכְ נִין", translation: "גר, שוכן/גרים, שוכנים" },
  { id: 59, word: "סַאּכְנֵה/סַ אּכְ נַאת", translation: "גרה, שוכנת/גרות, שוכנות" },
  { id: 60, word: "סֻּכַאן", translation: "תושבים" },
  { id: 61, word: "מֻשְכִלֵה/מַשַאּכֵל", translation: "בעיה/בעיות" },
  { id: 62, word: "הַוִיֵה/הַוִיַאת", translation: "תעודה/תעודות (אישית)" },
  { id: 63, word: "ּּבַיַארַה/ּּבַיַארַאת", translation: "פרדס/פרדסים" },
    { id: 72, word: "מַחְ'זַן", translation: "מחסן/מחסנים" },
    { id: 73, word: "מַטְּבַח'", translation: "מטבח/מטבחים" },
    { id: 74, word: "עֻ'רְפֵה", translation: "חדר/חדרים" },
    { id: 75, word: "בַּלְּכֹונֵה", translation: "מרפסת" },
    { id: 76, word: "דַרַגֵ'ה", translation: "מדרגה/מדרגות" },
    { id: 77, word: "מַלְגַ'א", translation: "מקלט (מחסה)/מקלטים" },
    { id: 78, word: "סַטֵח", translation: "גג/גגות" },
    { id: 79, word: "סַקֵפ", translation: "תקרה/תקרות" },
    { id: 80, word: "סֵיעַה", translation: "שעה" },
    { id: 81, word: "דְקִיקַה", translation: "דקה (זמן)" },
    { id: 82, word: "תַאנְיֵה", translation: "שניה/שניות" },
    { id: 83, word: "לֲחְטַ'ה", translation: "רגע/רגעים" },
    { id: 84, word: "מַּכְּתַּב", translation: "משרד/משרדים" },
    { id: 85, word: "מַּכְּתַּבֵה", translation: "ספריה, חנות ספרים" },
    { id: 86, word: "וַטִ'יפֵה", translation: "משרה/משרות (עבודה), מטלה, שיעורי בית" },
    { id: 87, word: "שַהַאדֵה", translation: "תעודה/תעודות (מקצוע, הוכרה וכדו')" },
    { id: 88, word: "קַמִיצ", translation: "חולצה מכופתרת/חולצות מכופתרות" },
    { id: 89, word: "בְּלוּזֵה", translation: "חולצת טריקו/חולצות טריקו" },
    { id: 90, word: "בַּנְטַלוֹן", translation: "מכנסיים" },
    { id: 91, word: "כֻּנְדַרַה", translation: "נעל/נעליים" },
    { id: 92, word: "עַמַארַה", translation: "בניין" },
    { id: 93, word: "טַאּבֵק", translation: "קומה/קומות" },
    { id: 94, word: "גַ'אר", translation: "שכן/שכנים" },
    { id: 1, word: "מַרַה", translation: "אישה" },
  { id: 2, word: "מַרַה", translation: "פעם/פעמים" },
  { id: 3, word: "רַגֻ'ל", translation: "גבר, איש/גברים, אנשים" },
  { id: 4, word: "אִנְסַאן", translation: "איש, בן אדם/אנשים, בני אדם (שם קיבוצי)" },
  { id: 5, word: "אֻם", translation: "אמא" },
  { id: 6, word: "אַב", translation: "אבא" },
  { id: 7, word: "עֵילֵה", translation: "משפחה (גרעינית)" },
  { id: 8, word: "ג'וּז", translation: "בעל" },
  { id: 9, word: "וֵין", translation: "איפה, היכן" },
  { id: 10, word: "גַ'מְב", translation: "ליד" },
  { id: 11, word: "כַמַן", translation: "גם / עוד" },
  { id: 12, word: "אַעְטַא", translation: "נתן" },
  { id: 13, word: "עַאפְיֵה", translation: "בריאות" },
  { id: 14, word: "גְ'דִיד", translation: "חדש/חדשים, גְ'דִידֵה - חדשה" },
  { id: 15, word: "קַדִים", translation: "ישן (זמן)/קַדִימֵה - ישנה" },
  { id: 16, word: "כְּבִיר", translation: "גדול/גדולים, כְּבִירֵה - גדולה" },
  { id: 17, word: "זְעִיר", translation: "קטן/קטנים, זְעִירֵה - קטנה" },
  { id: 18, word: "חַאסוּב/חַוַאסִיּב/כמביותר/כמביותרת", translation: "מחשב/מחשבים" },
  { id: 19, word: "חַארֵה", translation: "שכונה/שכונות" },
  { id: 20, word: "מַסְגֵ'ד", translation: "מסגד/מסגדים" },
  { id: 21, word: "חַ'זַאנֵה", translation: "ארון/ארונות, כספת/כספות" }

];

export default vocabularyPairs;
