export const vocabularyPairs = [
  { word: "צַּבַּאח אִלְחֵ'יר", translation: "בוקר טוב" },
  { word: "צַּבַּאח אִלְנוּר", translation: "בוקר אור" },
  { word: "מַסַא אִלְחֵ'יר", translation: "ערב טוב" },
  { word: "מַסַא אִלְנוּר", translation: "ערב אור" },
  { word: "מַרְחַבַּא", translation: "שלום רב" },
  { word: "מַרְחַבְּתֵין", translation: "רב שלומות" },
  { word: "אַהְלַן וְסַהְלַן", translation: "שלום וברכה" },
  { word: "אַהְלַן וְסַהְלַן בִּיכּ", translation: "שלום וברכה לך" },
  { word: "אִסֵם", translation: "שם" },
  { word: "אַסַאמִי", translation: "שמות" },
  { word: "אַמִיר", translation: "נסיך" },
  { word: "אֻמַרַא", translation: "נסיכים" },
  { word: "מְעַלֵם", translation: "מורה (זכר)" },
  { word: "מְעַלְמִין", translation: "מורים" },
  { word: "מְעַלְמֵה", translation: "מורה (נקבה)" },
  { word: "מְעַלְמַאת", translation: "מורות" },
  { word: "פִי", translation: "ב..." },
  { word: "מַע", translation: "עם" },
  { word: "דַוְרַה", translation: "קורס" },
  { word: "דַוְרַאת", translation: "קורסים" },
  { word: "טַאלֵבּ", translation: "סטודנט" },
  { word: "טֻלַאבּ", translation: "סטודנטים" },
  { word: "טַאלְבֵּה", translation: "סטודנטית" },
  { word: "טַאלִבַּאת", translation: "סטודנטיות" },
  { word: "גַ'אמְעַה", translation: "אוניברסיטה" },
  { word: "גַ'אמִעַאת", translation: "אוניברסיטאות" },
  { word: "סֵכְּרֵתֵירַא", translation: "מזכירה" },
  { word: "סֵכְּרֵתֵירַאת", translation: "מזכירות" },
  { word: "סֵכְּרֵתֵיר", translation: "מזכיר" },
  { word: "סֵכְּרֵתֵירִיוּן", translation: "מזכירים" },
  { word: "אַמִין", translation: "מזכיר של גוף רשמי, ישר/אמין" },
  { word: "אַמִינֵה", translation: "מזכירה של גוף רשמי, ישרה/אמינה" },
  { word: "מַדְרַסֵה", translation: "בית ספר" },
  { word: "מַדַארֵס", translation: "בתי ספר" },
  { word: "מֻדִיר", translation: "מנהל" },
  { word: "מֻדַרַא", translation: "מנהלים" },
  { word: "מֻדִירֵה", translation: "מנהלת" },
  { word: "מֻדִירַאת", translation: "מנהלות" },
  { word: "שִרְכֵּה", translation: "חברה" },
  { word: "שַרִכַּאת", translation: "חברות" },
  { word: "מֻחַאמִי", translation: "עו\"ד" },
  { word: "מֻחַאמִיֵין", translation: "עורכי דין" },
  { word: "מֻחַאמִיֵה", translation: "עורכת דין" },
  { word: "מֻחַאמִיַאת", translation: "עורכות דין" },
  { word: "וִזַארַה", translation: "משרד ממשלתי" },
  { word: "וִזַארַאת", translation: "משרדי ממשלה" },
  { word: "עַדֵל", translation: "צדק" },
  { word: "תִלְמִיז", translation: "תלמיד" },
  { word: "תַלַאמִיז", translation: "תלמידים" },
  { word: "תִלְמִיזֵה", translation: "תלמידה" },
  { word: "תִלְמִיזַאת", translation: "תלמידות" },
  { word: "צַאחֵבּ", translation: "חבר" },
  { word: "אַצְחַאבּ", translation: "חברים" },
  { word: "צַאחְבֵּה", translation: "חברה (ידידה)" },
  { word: "צַאחְבַּאת", translation: "חברות" },
  { word: "דַאר", translation: "בית" },
  { word: "דוּר", translation: "בתים" },
  { word: "וַלַד", translation: "ילד" },
  { word: "וְלַאד", translation: "ילדים" },
  { word: "אִבֵּן", translation: "בן" },
  { word: "אַבְּנַאא", translation: "בנים" },
  { word: "בִּנְת", translation: "ילדה / בת" },
  { word: "בַּנַאת", translation: "ילדות / בנות" },
];

export default vocabularyPairs;
